config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import os


def trigger_error(request):
    division_by_zero = 1 / 0


urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("reservations/", include("reservations.urls", namespace="reservation")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("lists/", include("lists.urls", namespace="lists")),
    path("conversations/", include("conversations.urls", namespace="conversations")),
    path('sentry-debug/', trigger_error),
    path(os.environ.get("ADMIN_URL", "admin/"), admin.site.urls),
]

if settings.DEBUG:
    # static을 이용해서 settgins.MEDIA_URL과 실제 사진이 저장된 폴더를 연결시켜 주었다
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views
from . import views

app_name = "core"

urlpatterns = [path("", room_views.HomeView.as_view(), name="home"),
               path("copyrights/", views.index, name="copyrights"),
               ]

reservations/urls.py
from django.urls import path
from . import views

app_name = "reservations"

urlpatterns = [
                path("create/<int:room>/<int:year>-<int:month>-<int:day>/", views.create, name="create"),
                path("<int:pk>/", views.ReservationDetailView.as_view(), name="detail"),
                path("<int:pk>/<str:verb>", views.edit_reservation, name="edit"),
                path("reservation-list/", views.ReservationList.as_view(), name="reservation-list"),
                path("reservation-manage/", views.ReservationManageList.as_view(), name="reservation-manage"),
]

rooms/urls.py
from django.urls import path
from . import views

app_name = "rooms"

urlpatterns = [
                path("create/", views.CreateRoomView.as_view(), name="crate"),
                path("<int:pk>/", views.RoomDetail.as_view(), name="detail"),
                path("<int:pk>/edit/", views.EditRoomView.as_view(), name="edit"),
                path("<int:pk>/photos/", views.RoomPhotosView.as_view(), name="photos"),
                path("<int:pk>/photos/add", views.AddPhotoView.as_view(), name="add-photo"),
                path(
                    "<int:room_pk>/photos/<int:photo_pk>/delete",
                    views.delete_photo,
                    name="delete-photos",
                ),
                path(
                    "<int:room_pk>/photos/<int:photo_pk>/edit",
                    views.EditPhotoView.as_view(),
                    name="edit-photo",
                ),
                path("search/", views.SearchView.as_view(), name="search")
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("login/github/", views.github_login, name="github-login"),
    path("login/github/callback/", views.github_callback, name="github-callback"),
    path("login/kakao/", views.kakao_login, name="kakao-login"),
    path("login/kakao/callback/", views.kakao_callback, name="kakao-callback"),
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("<int:pk>/", views.UserProfileView.as_view(), name="profile"),
    path("verify/<str:key>/", views.complete_verification, name="complete-verification"),
    path("update-profile/", views.UpdateProfileView.as_view(), name="update"),
    path("update-password/", views.UpdatePasswordView.as_view(), name="password"),
    path("switch-hosting/", views.switch_hosting, name="switch-hosting"),
    path("switch-language/", views.switch_language, name="switch-language"),
    path("wish-list/", views.SeeWishList.as_view(), name="see_wish_list"),
]

templates/partials/footer.html
{% load i18n %}
<div class="container mx-auto text-center pt-4 border-t font-light text-gray-400 text-sm flex items-center px-6">
    <div class="mr-8">
        <a href="{% url "core:copyrights" %}">{% trans "copyright" %}</a>
    </div>
    <div>
        {% get_current_language as LANGUAGE_CODE %}
        <select class="w-full h-6" id="js-lang">
            <option value="en" {% if LANGUAGE_CODE == 'en' %} selected {% endif %}>{% trans "English" %}</option>
            <option value="ko" {% if LANGUAGE_CODE == 'ko' %} selected {% endif %}>{% trans "Korean" %}</option>
        </select>
    </div>
</div>
<footer class="container mx-auto text-center py-10 font-medium text-gray-400">
    <div class="flex flex-col">
        <span>&copy; 2021 WooHome, Inc. {% trans "All rights reserved" %}.</span>
    </div>
</footer>

templates/partials/message.html
{% if messages %}
    <ul class="absolute mx-auto top-0 left-0 right-0 flex justify-center">
        {% for message in messages %}
        <li class="message font-medium bg-gray-700 rounded-full text-white py-4 px-6 z-10 w-64 text-center {% if message.tags %}{{ message.tags }}{% endif %}">{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}

templates/partials/nav.html
{% load i18n %}
<ul class="flex items-center text-sm font-medium h-full">
    {% if user.is_authenticated %}
        <li class="nav_link">
            <a href="{% url "users:switch-hosting" %}">
                {% if request.session.is_hosting %}
                    {% trans "Stop Hosting" %}
                {% else %}
                    {% trans "Start Hosting" %}
                {% endif %}
            </a>
        </li>
        {% if request.session.is_hosting %}
            <li class="nav_link"><a href="{% url 'rooms:crate' %}">{% trans "Create Room" %}</a> </li>
            <li class="nav_link"><a href="{% url 'reservations:reservation-manage' %}">{% trans "reservation management" %}</a></li>
        {% else %}
            <li class="nav_link"><a href="{% url "rooms:search" %}"><i class="fas fa-search-location"></i> {% trans "Search" %}</a></li>
            <li class="nav_link"><a href="{% url 'reservations:reservation-list' %}">{% trans "My reservation" %} ({{ user.reservations.count }})</a></li>
        {% endif %}
        <li class="nav_link"><a href="{% url 'users:see_wish_list' %}">{% trans "Wish List" %} ({{ user.list.rooms.count }})</a></li>
        <li class="nav_link"><a href="{{ user.get_absolute_url }}">{% trans "Profile" %}</a></li>
        <li class="nav_link"><a href="{% url "users:logout" %}">{% trans "Log out" %}</a></li>
    {% else %}
        <li class="nav_link"><a href="{% url "users:login" %}">{% trans "Log in" %}</a></li>
        <li class="nav_link"><a href="{% url "users:signup" %}">{% trans "Sign up" %}</a></li>
    {% endif %}
</ul>

templates/partials/social_login.html
{% load i18n %}
<div class="flex flex-col w-full">
{#    <span class="mb-1 text-sm text-gray-500 text-center">{% trans "😞GITHUB LOGIN CANNOT USE😞" %}</span>#}
    <a href="{% url 'users:github-login' %}" class="btn font-medium text-gray-700 mb-2 border-2 border-gray-700">
        <i class="fab fa-github-alt mr-2 fa-lg"></i>{% trans "Continue with Github" %}
    </a>
    <a href="{% url 'users:kakao-login' %}" class="btn font-medium text-yellow-700 mb-2 border-2 border-yellow-500 bg-yellow-200">
        <i class="fas fa-comment mr-2 fa-lg"></i>{% trans "Continue with Kakao" %}
    </a>
</div>

<div class="w-full flex items-center my-5">
    <div class="h-px w-full bg-gray-400"></div>
    <span class="text-gray-600 font-medium mx-4 text-sm">or</span>
    <div class="h-px w-full bg-gray-400"></div>
</div>