config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import os


def trigger_error(request):
    division_by_zero = 1 / 0


urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("reservations/", include("reservations.urls", namespace="reservation")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("lists/", include("lists.urls", namespace="lists")),
    path("conversations/", include("conversations.urls", namespace="conversations")),
    path('sentry-debug/', trigger_error),
    path(os.environ.get("ADMIN_URL", "admin/"), admin.site.urls),
]

if settings.DEBUG:
    # static을 이용해서 settgins.MEDIA_URL과 실제 사진이 저장된 폴더를 연결시켜 주었다
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views
from . import views

app_name = "core"

urlpatterns = [path("", room_views.HomeView.as_view(), name="home"),
               path("copyrights/", views.index, name="copyrights"),
               ]

lists/urls.py
from django.urls import path
from . import views

app_name = "lists"

urlpatterns = [
    path("toggle/<int:room_pk>", views.toggle_room, name="toggle-room"),
]

reservations/urls.py
from django.urls import path
from . import views

app_name = "reservations"

urlpatterns = [
                path("create/<int:room>/<int:year>-<int:month>-<int:day>/", views.create, name="create"),
                path("<int:pk>/", views.ReservationDetailView.as_view(), name="detail"),
                path("<int:pk>/<str:verb>", views.edit_reservation, name="edit"),
                path("reservation-list/", views.ReservationList.as_view(), name="reservation-list"),
                path("reservation-manage/", views.ReservationManageList.as_view(), name="reservation-manage"),
]

rooms/urls.py
from django.urls import path
from . import views

app_name = "rooms"

urlpatterns = [
                path("create/", views.CreateRoomView.as_view(), name="crate"),
                path("<int:pk>/", views.RoomDetail.as_view(), name="detail"),
                path("<int:pk>/edit/", views.EditRoomView.as_view(), name="edit"),
                path("<int:pk>/photos/", views.RoomPhotosView.as_view(), name="photos"),
                path("<int:pk>/photos/add", views.AddPhotoView.as_view(), name="add-photo"),
                path(
                    "<int:room_pk>/photos/<int:photo_pk>/delete",
                    views.delete_photo,
                    name="delete-photos",
                ),
                path(
                    "<int:room_pk>/photos/<int:photo_pk>/edit",
                    views.EditPhotoView.as_view(),
                    name="edit-photo",
                ),
                path("search/", views.SearchView.as_view(), name="search")
]

rooms/models.py
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django_countries.fields import CountryField
from django.urls import reverse
from imagekit.models import ImageSpecField
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from core import models as core_models
from cal import Calendar


class AbstractItem(core_models.TimeStampedModel):
    """ Abstract Item """

    name = models.CharField(max_length=100)

    class Meta:
        abstract = True

    def __str__(self):
        return self.name


class RoomType(AbstractItem):
    """ RoomType Object Definition """

    pass

    class Meta:
        verbose_name = _("Room Type")
        ordering = ["name"]


class Amenity(AbstractItem):
    """ Amenity Object Definition """

    pass

    class Meta:
        verbose_name_plural = _("Amenities")


class Facility(AbstractItem):
    """ Facility Model Definition """

    pass

    class Meta:
        verbose_name_plural = _("Facilities")


class HouseRule(AbstractItem):
    """ HouseRule Model Definition """

    pass

    class Meta:
        verbose_name = _("House Rule")


class Photo(core_models.TimeStampedModel):
    """ Photo Model Definition """

    caption = models.CharField(max_length=80)
    # file = models.ImageField(upload_to="room_photos")
    file = ProcessedImageField(upload_to="room_photos",
                               processors=[ResizeToFill(1024, 1024)],
                               options={'quality': 60})
    room = models.ForeignKey("Room", related_name="photos", on_delete=models.CASCADE)

    def __str__(self):
        return self.caption


class Room(core_models.TimeStampedModel):
    """ Room Model Definition """

    name = models.CharField(_("name"), max_length=25)  # 이름
    description = models.TextField(_("description"), )  # 설명
    country = CountryField(_("country"), )  # 나라
    city = models.CharField(_("city"), max_length=20)  # 도시
    price = models.IntegerField(_("price"), )  # 가격
    address = models.CharField(_("address"), max_length=30)  # 주소
    guests = models.IntegerField(_("guests"), )  # 게스트
    beds = models.IntegerField(_("beds"), )  # 침대
    bedrooms = models.IntegerField(_("bedrooms"), )  # 침실
    baths = models.IntegerField(_("baths"), )  # 화장실
    check_in = models.TimeField(_("check_in"), )
    check_out = models.TimeField(_("check_out"), )
    instant_book = models.BooleanField(_("instant_book"), default=False)
    host = models.ForeignKey("users.User", related_name="rooms", on_delete=models.CASCADE)
    room_type = models.ForeignKey("RoomType", related_name="rooms", on_delete=models.CASCADE)
    amenities = models.ManyToManyField("Amenity", related_name="rooms", blank=True)
    facilities = models.ManyToManyField("Facility", related_name="rooms", blank=True)
    house_rules = models.ManyToManyField("HouseRule", related_name="rooms", blank=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.city = str.capitalize(self.city)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("rooms:detail", kwargs={"pk": self.pk})

    def total_rating(self):
        all_reviews = self.reviews.all()
        all_rating = 0
        for review in all_reviews:
            all_rating += review.rating_average()
        if all_rating == 0:
            return 0
        else:
            length = len(all_reviews)
            return round(all_rating / length, 2)

    def first_photo(self):
        try:
            photo, = self.photos.all()[:1]
            return photo.file.url
        except ValueError:
            return None

    def get_next_four_photos(self):
        try:
            photos = self.photos.all()[1:5]
        except ValueError:
            return None
        return photos

    def get_calendars(self):
        now = timezone.now()
        this_year = now.year
        this_month = now.month
        next_month = now.month + 1
        if this_month == 12:
            next_month = 1
        this_month_cal = Calendar(this_year, this_month)
        next_month_cal = Calendar(this_year, next_month)
        return [this_month_cal, next_month_cal]

    class Meta:
        ordering = ('name',)

rooms/forms.py
from django import forms
from . import models
from django.utils.translation import gettext_lazy as _
from django_countries.fields import CountryField


class SearchForm(forms.Form):

    city = forms.CharField(initial=_("Anywhere"))
    country = CountryField(default="KR").formfield()
    room_type = forms.ModelChoiceField(
        required=False, empty_label=_("Any kind"), queryset=models.RoomType.objects.all()
    )
    price = forms.IntegerField(
        required=False, widget=forms.NumberInput(attrs={"placeholder": _("Max Price ($)")})
    )


class CreatePhotoForm(forms.ModelForm):

    class Meta:
        model = models.Photo
        fields = (
            "caption",
            "file",
        )

    def save(self, pk, *args, **kwargs):
        photo = super().save(commit=False)
        room = models.Room.objects.get(pk=pk)
        photo.room = room
        photo.save()


class CreateRoomForm(forms.ModelForm):
    class Meta:
        model = models.Room
        fields = (
            "name",
            "description",
            "country",
            "city",
            "price",
            "address",
            "guests",
            "beds",
            "bedrooms",
            "baths",
            "check_in",
            "check_out",
            "instant_book",
            "room_type",
            "amenities",
            "facilities",
            "house_rules",
        )

    def save(self, *args, **kwargs):
        room = super().save(commit=False)
        return room

rooms/views.py
from django.views.generic import ListView, DetailView, View, UpdateView, FormView
from django.utils import timezone
from django.shortcuts import render, redirect, reverse
from django.core.paginator import Paginator
from django.http import Http404
from django.utils.translation import gettext_lazy as _
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from . import forms
from . import models
from users import mixins as user_mixins


class HomeView(ListView):
    """ HomeView Definition """

    model = models.Room
    paginate_by = 8
    ordering = "name"
    paginate_orphans = 4
    page_kwarg = "page"
    context_object_name = "rooms"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        now = timezone.now()
        context["now"] = now
        return context


# @login_required()
class RoomDetail(DetailView):
    """ RoomDetail Definition """

    model = models.Room


class SearchView(View):

    def get(self, request):
        city = request.GET.get("city")

        if city:

            form = forms.SearchForm(request.GET)

            if form.is_valid():

                city = form.cleaned_data.get("city")
                country = form.cleaned_data.get("country")
                room_type = form.cleaned_data.get("room_type")
                price = form.cleaned_data.get("price")

                filter_args = {}

                if city != "Anywhere" and city != "제한없음":
                    filter_args["city__startswith"] = city

                filter_args["country"] = country

                if price is not None:
                    filter_args["price__lte"] = price

                if room_type is not None:
                    filter_args["room_type"] = room_type

                rooms = models.Room.objects.filter(**filter_args)

                qs = rooms.order_by("-created")

                paginator = Paginator(qs, 10, 5)

                page = request.GET.get("page", 1)

                if rooms.count() == 0:
                    rooms = None
                else:
                    rooms = paginator.get_page(page)

                return render(
                    request,
                    "rooms/search.html",
                    {
                        "form": form,
                        "rooms": rooms,
                    },
                )

        else:
            form = forms.SearchForm()

        return render(request, "rooms/search.html",
                      {
                          "form": form,
                          "rooms": None,
                      })


class EditRoomView(user_mixins.LoggedInOnlyView, UpdateView):
    model = models.Room
    template_name = 'rooms/room_edit.html'
    fields = (
        "name",
        "description",
        "country",
        "city",
        "price",
        "address",
        "guests",
        "beds",
        "bedrooms",
        "baths",
        "check_in",
        "check_out",
        "instant_book",
        "room_type",
        "amenities",
        "facilities",
        "house_rules",
    )

    def get_object(self, queryset=None):
        room = super().get_object(queryset=queryset)
        if room.host.pk != self.request.user.pk:
            raise Http404()
        return room


class RoomPhotosView(user_mixins.LoggedInOnlyView, RoomDetail):
    model = models.Room
    template_name = 'rooms/room_photos.html'

    def get_object(self, queryset=None):
        room = super().get_object(queryset=queryset)
        if room.host.pk != self.request.user.pk:
            raise Http404()
        return room


@login_required
def delete_photo(request, room_pk, photo_pk):
    user = request.user
    try:
        room = models.Room.objects.get(pk=room_pk)
        if room.host.pk != user.pk:
            messages.error(request, _("Can't delete that photo"))
        else:
            models.Photo.objects.filter(pk=photo_pk).delete()
            messages.success(request, _("Photo Deleted"))
        return redirect(reverse("rooms:photos", kwargs={"pk": room_pk}))
    except models.Room.DoesNotExist:
        return redirect(reverse("core:home"))


class EditPhotoView(user_mixins.LoggedInOnlyView, SuccessMessageMixin, UpdateView):
    model = models.Photo
    template_name = "rooms/photo_edit.html"
    pk_url_kwarg = "photo_pk"
    fields = ("caption",)
    success_message = _("Photo Updated")

    def get_success_url(self):
        room_pk = self.kwargs.get("room_pk")
        return reverse("rooms:photos", kwargs={"pk": room_pk})


class AddPhotoView(user_mixins.LoggedInOnlyView, SuccessMessageMixin, FormView):
    model = models.Photo
    template_name = "rooms/photo_create.html"
    fields = (
        _("caption"),
        _("file"),
    )
    form_class = forms.CreatePhotoForm

    def form_valid(self, form):
        pk = self.kwargs.get('pk')
        form.save(pk)
        messages.success(self.request, _("Photo Uploaded"))
        return redirect(reverse("rooms:photos", kwargs={"pk": pk}))


class CreateRoomView(user_mixins.LoggedInOnlyView, FormView):
    form_class = forms.CreateRoomForm
    template_name = "rooms/room_create.html"

    def form_valid(self, form):
        room = form.save()
        room.host = self.request.user
        room.save()
        form.save_m2m()
        messages.success(self.request, _("Room Created"))
        return redirect(reverse("rooms:detail", kwargs={'pk': room.pk}))

templates/rooms/photo_create.html
{%  extends "base.html" %}
{% load i18n %}

{% block page_title %}
    {% trans "upload photo" %}
{% endblock %}

{% block search-bar %}
{% endblock %}

{% block content %}

    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">

        {% include 'mixins/room/room_form.html' with form=form cta="upload photo" %}

    </div>
{% endblock %}

templates/rooms/photo_edit.html
{%  extends "base.html" %}
{% load i18n %}

{% block page_title %}
    {% trans "update photo" %}
{% endblock %}

{% block search-bar %}
{% endblock %}

{% block content %}

    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">

        {% include 'mixins/room/room_form.html' with form=form cta="Update photo" %}

    </div>
{% endblock %}

templates/rooms/room_create.html
{%  extends "base.html" %}
{% load i18n %}

{% block page_title %}
    {% trans "create room" %}
{% endblock %}

{% block search-bar %}
{% endblock %}

{% block content %}

    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">

        {% include 'mixins/room/room_form.html' with form=form cta="create room" %}

    </div>
{% endblock %}

templates/rooms/room_detail.html
{% extends "base.html" %} 
{% load is_booked on_favs i18n on_reserv manage_reserv %}

{% block page_title %}
  {{ room.name }}
{% endblock %}

{% block content %}

    <div class="-mt-5 container max-w-full h-75vh flex mb-20">
        <div class="h-full w-1/2 bg-center bg-cover" style="background-image: url({{ room.first_photo }})"></div>
        <div class="h-full w-1/2 flex flex-wrap">
            {% for photo in room.get_next_four_photos %}
                <div style="background-image: url({{ photo.file.url }})" class="w-1/2 h-auto bg-cover bg-center border border-gray-700"></div>
            {% endfor %}
        </div>
    </div>

    <div class="container mx-auto flex justify-around pb-56">
        <div class="w-1/2">
            <div class="flex justify-between">
                <div class="mb-5">
                    <h4 class="text-3xl font-medium mb-1">{{ room.name }}</h4>
                    <span class="text-gray-700 font-light">{{ room.city }}</span>
                    {% on_favs room as on_fav_boolean %}
                    {% if on_fav_boolean %}
                        <a class="block mt-8 w-full mb-10 text-base text-blue-500"
                       href="{% url 'lists:toggle-room' room.pk %}?action=remove">
                            <i class="far fa-check-circle mr-2"></i>
                            {% trans "Remove from Favorites" %}
                        </a>
                    {% else %}
                        <a class="block mt-8 w-full mb-10 text-base text-red-500"
                       href="{% url 'lists:toggle-room' room.pk %}?action=add">
                        {% trans "Save to Favorites" %}
                        </a>
                    {% endif %}
                </div>
                <div class="flex flex-col items-center">
                    <a href="{{ room.host.get_absolute_url }}">
                        {% include "mixins/user_avatar.html" with user=room.host %}
                    </a>
                    <span class="mt-2 text-gray-500">{{ room.host.first_name }}</span>
                </div>
            </div>
            <div class="border-section flex">
                <span class="mr-6 font-light">{{ room.room_type }}</span>
                <span class="mr-6 font-light">{{ room.beds }} {% trans "bed" %}</span>
                <span class="mr-6 font-light">{{ room.bedrooms }} {% trans "bedroom" %}</span>
                <span class="mr-6 font-light">{{ room.guests }} {% trans "guest" %}</span>
                <span class="mr-6 font-light">{{ room.baths }} {% trans "bath" %}</span>
            </div>
            <p class="border-section">
                {{ room.description }}
            </p>
            <div class="border-section">
                <h4 class="font-medium text-lg mb-5">{% trans "Amenities" %}</h4>
                {% for a in room.amenities.all %}
                    <li class="mb-2">{{ a }}</li>
                {% endfor %}
            </div>
            <div class="border-section">
                <h4 class="font-medium text-lg mb-5">{% trans "Facilities" %}</h4>
                {% for f in room.facilities.all %}
                    <li class="mb-2">{{ f }}</li>
                {% endfor %}
            </div>
            <div class="border-section">
                <h4 class="font-medium text-lg mb-5">{% trans "House Rules" %}</h4>
                {% for h in room.house_rules.all %}
                    <li class="mb-2">{{ h }}</li>
                {% endfor %}
            </div>
            <div class="mt-10">
                <h4 class="font-medium text-2xl mb-5">{% trans "Reviews" %}</h4>
                <div class="flex items-center">
                    <div>
                        <i class="fas fa-star text-green-500"></i>
                        <span class="font-bold text-xl">{{ room.total_rating }}</span>
                    </div>
                    <div class="h-4 w-px bg-gray-400 mx-5"></div>
                    <div>
                        <span class="font-bold text-xl">{{ room.reviews.count }}</span>
                        <span>{% trans "reviews" %}</span>
                    </div>
                </div>
                <div class="mt-10">
                    {% for review in room.reviews.all %}
                        <div class="border-section">
                            <div class="mb-3 flex">
                                <div>
                                    {% include "mixins/user_avatar.html" with user=review.user h_and_w='w-10 h-10' text='text-xl'%}
                                </div>
                                <div class="flex flex-col ml-5">
                                    <span class="font-medium">{{ review.user.first_name }}</span>
                                    <span class="text-sm text-gray-500">{{ review.created|date:'F Y' }}</span>
                                </div>
                            </div>
                            <div>
                                <i class="fas fa-star text-xs text-green-400"></i>
                                <span class="font-medium text-sm">{{ review.rating_average }}</span>
                            </div>
                            <p>{{ review.review }}</p>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="w-1/3">
            {% if room.host == user %}
                <a href="{% url 'rooms:edit' room.pk %}" class="btn-link block">{% trans "Edit Room" %}</a>
            {% else %}
                {% if not request.session.is_hosting %}
                    <div class="border-b border-gray-400 w-5/6 ml-8 mb-12 mt-8 p-8">
                        <div class="font-medium text-lg block mb-8 text-center">
                            <span class="text-lg">{% trans "PRICE" %}</span>
                        </div>
                        <div class="justify-between text-lg flex">
                            <div><span>$ {{ room.price }}</span></div>
                            <div><span>/</span></div>
                            <div><span>{% trans "DAY" %}</span></div>
                        </div>
                    </div>
                    {% for calendar in room.get_calendars %}
                        <div class="mb-20 ml-8 w-5/6">
                            <span class="text-center font-medium text-lg block mb-8">
                                {{ calendar.get_month }} / {{ calendar.year }}
                            </span>
                            <div class="cal-grid font-bold mb-4 text-center">
                                {% for day in calendar.day_names %}
                                    <span>{{ day }}</span>
                                {% endfor %}
                            </div>
                            <div class="cal-grid">
                                {% for day in calendar.get_days %}
                                    {% is_booked room day as is_booked_bool %}
                                    {% if day.number != 0 %}
                                        {% if day.past %}
                                            <span class="rounded bg-gray-200 w-full p-1 text-center text-gray-300 font-extralight">
                                                {{ day }}
                                            </span>
                                        {% elif is_booked_bool %}
                                            <span class="rounded bg-gray-200 w-full p-1 text-center text-gray-400 font-extralight line-through">
                                                {{ day }}
                                            </span>
                                        {% else %}
                                            <a href="{% url 'reservations:create' room.pk day.year day.month day.number %}"
                                               class="bg-gray-200 font-normal w-full text-center rounded text-gray-700 p-1
                                            hover:bg-green-400 hover:text-white hover:cursor-pointer">
                                                {{ day }}
                                            </a>
                                        {% endif %}
                                    {% else %}
                                        <span></span>
                                    {% endif %}
                                {% endfor %}

                            </div>
                        </div>
                    {% endfor %}

                {% endif %}
            {% endif %}
        </div>
    </div>

{% endblock %}

templates/rooms/room_edit.html
{%  extends "base.html" %}
{% load i18n %}

{% block page_title %}
    {% trans "Room Edit" %}
{% endblock %}

{% block search-bar %}
{% endblock %}

{% block content %}

    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">

        {% include 'mixins/room/room_form.html' with form=form cta="Update room" %}

        <div class="mt-5">
            <a href="{% url 'rooms:photos' room.pk %}" class="text-green-500 font-medium">{% trans "Edit Photos" %}</a>
        </div>

    </div>
{% endblock %}

templates/rooms/room_list.html
{% extends "base.html" %}
{% load i18n %}

{% block page_title %}
    HOME
{% endblock %}

{% block content %}

    <div class="container mx-auto pb-30">

        <div class="container rounded-xl -mx-30 bg-gray-800 w-full h-50vh mt-32 mb-24 bg-cover bg-center" style="background-image:url(https://images.unsplash.com/photo-1540998145333-e2eef1a9822d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1533&q=80)"></div>

        <div class="flex flex-wrap -mx-30 mb-10">
            {% for room in rooms %}
                {% include 'mixins/room_card.html' with room=room %}
            {% endfor %}
        </div>

        <div class="flex item-center justify-center mb-8">
            {% if page_obj.has_previous %}
                <a class="mr-3" href="?page=">
                    <i class="fas fa-angle-double-left"></i>
                </a>
                <a href="?page={{ page_obj.previous_page_number }}" class="text-green-600">
                    <i class="fas fa-arrow-left"></i>
                </a>
            {% endif %}

            <span class="mx-3 font-medium text-lg">
                {% blocktrans with current_page=page_obj.number total_page=page_obj.paginator.num_pages %}Page {{ current_page }} of {{ total_page }}{% endblocktrans %}
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}" class="text-green-600">
                    <i class="fas fa-arrow-right"></i>
                </a>
                <a class="ml-3" href="?page={{ page_obj.paginator.num_pages }}">
                    <i class="fas fa-angle-double-right"></i>
                </a>
            {% endif %}
        </div>

    </div>
{% endblock content %}

templates/rooms/room_photos.html
{%  extends "base.html" %}
{% load i18n %}

{% block page_title %}
    {{ room.name }}{% trans "'s Photos" %}
{% endblock %}

{% block search-bar %}
{% endblock %}

{% block content %}

    <div class="container mx-auto my-10 flex flex-col items-center">

        <div class="my-10 w-4/5">
            <a href="{% url "rooms:add-photo" room.pk %}" class="btn-link w-1/6 block">{% trans "Upload Photo" %}</a>
        </div>

        {% for photo in room.photos.all %}
            <div class="mb-5 border p-6 border-gray-400 flex justify-between w-4/5">
                <div class="flex items-start">
                    <img src="{{ photo.file.url }}" class="w-28 h-28"/>
                    <span class="ml-5 text-xl">{{ photo.caption }}</span>
                </div>
                <div class="flex flex-col w-1/5">
                    <a class="btn-link mb-5 bg-green-500" href="{% url 'rooms:edit-photo' room.pk photo.pk %}">{% trans "Edit" %}</a>
                    <a class="btn-link bg-red-600" href="{% url 'rooms:delete-photos' room.pk photo.pk %}">{% trans "Delete" %}</a>
                </div>
            </div>
        {% endfor %}

        <div class="flex justify-center">
            <a href="{% url "rooms:edit" room.pk %}" class="text-green-500 font-medium font-2xl">{% trans "Back to Edit room" %}</a>
        </div>

    </div>
{% endblock %}

templates/rooms/search.html
{%  extends "base.html" %}
{% load i18n %}

{% block page_title %}
    {% trans "Search" %}
{% endblock %}

{% block search-bar %}
    {# search결과창에서는 search-bar 숨기기 #}
{% endblock %}

{% block content %}

        <div class="py-8 flex flex-col items-center border-gray-400">
            <div class="flex items-center">
                <h3 class="text-2xl">{% trans "Search for the Room You want" %}</h3>
            </div>
        </div>

        <div class="container lg:w-2/3 md:w-1/2 mx-auto my-4 p-4 flex flex-col text-sm items-center border border-gray-400">

            <div class="max-h-full overflow-auto">
                <form method="get" action="{% url "rooms:search" %}">
                    {{ form.as_p }}
                    <button class="btn-link mt-8">Search</button>
                </form>
            </div>
        </div>

    <div class="items-center text-center">
        <div>
            <span class="text-2xl font-bold">{% trans "Results" %}</span>
        </div>
        <div class="container lg:w-2/3 md:w-1/2 mx-auto my-4 p-4 flex text-sm items-center border border-gray-400">
            {% if rooms is None %}
                <span class="text-lg font-base">{% trans "No Matching Rooms.." %}</span>
            {% else %}
                {% for room in rooms %}
                    {% include 'mixins/room_card.html' with room=room %}
                {% endfor %}
            {% endif %}

        </div>
    </div>

{% endblock %}