config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import os


def trigger_error(request):
    division_by_zero = 1 / 0


urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("reservations/", include("reservations.urls", namespace="reservation")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("lists/", include("lists.urls", namespace="lists")),
    path("conversations/", include("conversations.urls", namespace="conversations")),
    path('sentry-debug/', trigger_error),
    path(os.environ.get("ADMIN_URL", "admin/"), admin.site.urls),
]

if settings.DEBUG:
    # static을 이용해서 settgins.MEDIA_URL과 실제 사진이 저장된 폴더를 연결시켜 주었다
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

conversations/urls.py
from django.urls import path
from . import views


app_name = "conversations"

urlpatterns = (
    path("go/<int:r_pk>/<int:a_pk>/<int:b_pk>", views.go_conversations, name="go"),
    path("<int:pk>/<int:r_pk>", views.ConversationsDetailView.as_view(), name="detail"),
)

core/urls.py
from django.urls import path
from rooms import views as room_views
from . import views

app_name = "core"

urlpatterns = [path("", room_views.HomeView.as_view(), name="home"),
               path("copyrights/", views.index, name="copyrights"),
               ]

reservations/urls.py
from django.urls import path
from . import views

app_name = "reservations"

urlpatterns = [
                path("create/<int:room>/<int:year>-<int:month>-<int:day>/", views.create, name="create"),
                path("<int:pk>/", views.ReservationDetailView.as_view(), name="detail"),
                path("<int:pk>/<str:verb>", views.edit_reservation, name="edit"),
                path("reservation-list/", views.ReservationList.as_view(), name="reservation-list"),
                path("reservation-manage/", views.ReservationManageList.as_view(), name="reservation-manage"),
]

reservations/models.py
import datetime
from django.db import models
from django.utils import timezone
from core import models as core_models
from django.utils.translation import gettext_lazy as _


class BookedDay(core_models.TimeStampedModel):

    day = models.DateField()
    reservation = models.ForeignKey("Reservation", on_delete=models.CASCADE)

    class Meta:
        verbose_name = _("Booked Day")
        verbose_name_plural = _("Booked Days")

    def __str__(self):
        return str(self.day)


class Reservation(core_models.TimeStampedModel):

    """ Reservation Model Definition """

    STATUS_PENDING = "pending"
    STATUS_CONFIRMED = "confirmed"
    STATUS_CANCELED = "canceled"

    STATUS_CHOICES = (
        (STATUS_PENDING, _("Pending")),
        (STATUS_CONFIRMED, _("Confirmed")),
        (STATUS_CANCELED, _("Canceled")),
    )

    status = models.CharField(_("status"), max_length=12, choices=STATUS_CHOICES, default=STATUS_PENDING)
    guest = models.ForeignKey(
        "users.User", related_name="reservations", on_delete=models.CASCADE, null=True
    )
    room = models.ForeignKey(
        "rooms.Room", related_name="reservations", on_delete=models.CASCADE, null=True
    )
    check_in = models.DateField(_("check_in"), null=True, blank=True)
    check_out = models.DateField(_("check_out"), null=True, blank=True)

    def __str__(self):
        return f"{self.room} : {self.check_in} - {self.check_out}"

    def in_progress(self):
        now = timezone.now().date()
        return self.check_in <= now <= self.check_out

    in_progress.boolean = True

    def is_finished(self):
        now = timezone.now().date()
        is_finished = now > self.check_out
        if is_finished:
            BookedDay.objects.filter(reservation=self).delete()
        return is_finished

    is_finished.boolean = True

    def save(self, *args, **kwargs):

        if self.pk is None:
            start = self.check_in
            end = self.check_out
            difference = end - start
            existing_booked_day = BookedDay.objects\
                .filter(day__range=(start, end))\
                .filter(reservation__room__pk=self.room.pk)\
                .exists()
            if not existing_booked_day:
                super().save(*args, **kwargs)
                for i in range(difference.days + 1):
                    day = start + datetime.timedelta(days=i)
                    BookedDay.objects.create(day=day, reservation=self)
                return
        return super().save(*args, **kwargs)

reservations/views.py
import datetime
from django.utils.translation import gettext_lazy as _
from django.http import Http404
from django.views.generic import View, TemplateView
from django.contrib import messages
from django.shortcuts import render, redirect, reverse
from . import models
from users import models as user_models
from rooms import models as room_models
from reviews import forms as review_forms


class CreateError(Exception):
    pass


def create(request, room, year, month, day):
    try:
        date_obj = datetime.datetime(year, month, day)
        room = room_models.Room.objects.get(pk=room)
        models.BookedDay.objects.get(day=date_obj, reservation__room=room)
        raise CreateError()
    except (room_models.Room.DoesNotExist, CreateError):
        messages.error(request, _("Can't Reserve That Room"))
        return redirect(reverse("core:home"))
    except models.BookedDay.DoesNotExist:
        reservation = models.Reservation.objects.create(
            guest=request.user,
            room=room,
            check_in=date_obj,
            check_out=date_obj + datetime.timedelta(days=1),
        )
        return redirect(reverse("reservations:detail", kwargs={"pk": reservation.pk}))


class ReservationDetailView(View):
    def get(self, *args, **kwargs):
        pk = kwargs.get('pk')
        reservation = models.Reservation.objects.get_or_none(pk=pk)
        if (reservation.guest != self.request.user and reservation.room.host != self.request.user) \
                or reservation is None:
            raise Http404()
        user = self.request.user
        form = review_forms.CreateReviewForm()
        return render(self.request, "reservation/detail.html", {'reservation': reservation, 'form': form, 'user': user})


def edit_reservation(request, pk, verb):
    reservation = models.Reservation.objects.get_or_none(pk=pk)
    if (reservation.guest != request.user and reservation.room.host != request.user) \
            or reservation is None:
        raise Http404()
    if verb == "confirm":
        reservation.status = models.Reservation.STATUS_CONFIRMED
    elif verb == "cancel":
        reservation.status = models.Reservation.STATUS_CANCELED
        models.BookedDay.objects.filter(reservation=reservation).delete()
    elif verb == "pending":
        reservation.status = models.Reservation.STATUS_PENDING
        # models.BookedDay.objects.filter(reservation=reservation).delete()
    reservation.save()
    messages.success(request, "Reservation Updated")
    return redirect(reverse("reservations:detail", kwargs={"pk": reservation.pk}))


class ReservationList(TemplateView):
    model = user_models.User
    template_name = "reservation/reservation_list.html"


class ReservationManageList(TemplateView):
    model = user_models.User
    template_name = "reservation/reservation_manage_list.html"

templates/reservation/detail.html
{%  extends "base.html" %}
{% load i18n %}

{% block page_title %}
    {% trans "Reservation" %} {{ reservation.chekc_in }}
{% endblock %}

{% block search-bar %}
{% endblock %}

{% block content %}

    <div class="mt-10 ml-20">
        <span class="text-green-600 font-medium items-center">
            <a href="{% url 'rooms:detail' reservation.room.pk %}"><i class="fas fa-arrow-left"></i>{% trans " go back to room" %}</a>
        </span>
    </div>
    <div class="container mx-auto my-2 flex flex-col">

        <div class="bg-cover bg-center h-56 rounded-t-lg" style="background-image: url({{ reservation.room.first_photo }});"></div>

        <div class="flex flex-col items-start border-l border-r border-t border-b">
            <div class="font-medium border-b py-8 px-5 w-full">
                {{ reservation.check_in }} - {{ reservation.check_out }}
                <span class="ml-5 \
                    {% if reservation.status == 'pending' %} text-yellow-600 \
                    {% elif reservation.status == 'canceled' %} text-red-600 \
                    {% else %} text-green-600 \
                    {% endif %}">
                    {{ reservation.get_status_display }}
                </span>
            </div>

            <span class="text-2xl border-b p-5 mt-2 w-full">
                {{ reservation.room.name }}
            </span>

            <div class="flex p-5 border-b w-full">
                <div class="flex flex-col items-center">
                    {% include "mixins/user_avatar.html" with user=reservation.room.host %}
                    <span class="mt-2 text-gray-500">{{ reservation.room.host.first_name }}</span>
                </div>
                <div class="ml-5 flex flex-col">
                    {% if reservation.room.host.pk != user.pk %}
                    <span class="font-medium mb-px">{% trans "Contact your WooHome Host" %}</span>
                    {% else %}
                    <span class="font-medium mb-px">{% trans "Contact your WooHome Guest" %}</span>
                    {% endif %}
                    <a href="{% url 'conversations:go' reservation.pk reservation.room.host.pk reservation.guest.pk %}"
                       class="font-medium text-green-500">
                        {% trans "Send a Message" %}
                    </a>
                </div>
            </div>

        <div class="py-10 px-5">
            {% if reservation.status != 'canceled' %}
                {% if reservation.status == 'confirmed' and reservation.is_finished %}
                    <span class="font-medium text-2lg text-center w-full block mb-5">{% trans "Write your review" %}</span>
                    <form action="{% url 'reviews:create' reservation.room.pk %}" method="POST" class="w-1/3 mx-auto">
                        {% csrf_token %}
                        {{ form }}
                        <button class="btn-link mt-5">{% trans "Submit Review" %}</button>
                    </form>
                {% else %}
                    {% if reservation.status == 'pending' and reservation.room.host != user %}
                        <a href="{% url 'reservation:edit' reservation.pk 'cancel' %}" class="btn-link block px-3 mb-5">{% trans "Cancel Reservation" %}</a>
                    {% elif reservation.status == 'pending' and reservation.room.host == user %}
                        <a href="{% url 'reservation:edit' reservation.pk 'confirm' %}" class="btn-link block px-3 mb-5">{% trans "Approve Reservation" %}</a>
                        <a href="{% url 'reservation:edit' reservation.pk 'cancel' %}" class="btn-link block px-3 mb-5">{% trans "Decline Reservation" %}</a>
                    {% elif reservation.room.host == user %}
                        <a href="{% url 'reservation:edit' reservation.pk 'pending' %}" class="btn-link block px-3 mb-5">{% trans "Pending Reservation" %}</a>
                        <a href="{% url 'reservation:edit' reservation.pk 'cancel' %}" class="btn-link block px-3 mb-5">{% trans "Cancel Reservation" %}</a>
                    {% endif %}
                {% endif %}
            {% elif reservation.room.host == user %}
                <a href="{% url 'reservation:edit' reservation.pk 'confirm' %}" class="btn-link block px-3 mb-5">{% trans "Approve Reservation" %}</a>
                <a href="{% url 'reservation:edit' reservation.pk 'pending' %}" class="btn-link block px-3 mb-5">{% trans "Pending Reservation" %}</a>
            {% endif %}
        </div>

        </div>


    </div>

{% endblock %}

templates/reservation/reservation_list.html
{% extends "base.html" %}
{% load i18n %}

{% block page_title %}
    {% trans "Reservation List" %}
{% endblock %}

{% block content %}

    <div class="container mx-auto pb-30">

        <div class="py-12 flex flex-col items-center border-gray-400">
            <div class="flex items-center">
                <h3 class="text-2xl">{{ user.first_name }}{% trans "'s Reservation Room List" %}</h3>
            </div>
        </div>

        <div class="grid md:grid-cols-3 w-full -mx-30 mb-10 items-center">
            {% if user.reservations.count > 0 %}
                {% for reservation in user.reservations.all %}
                    <div class="w-screen px-10">
                        <a class="ml-6 mb-4 text-base text-xl font-medium text-white bg-green-400 hover:bg-indigo-400 p-1 rounded-md"
                           href="{% url 'reservations:detail' reservation.pk %}">
                            {% trans "Manage Reservation" %}
                        </a>
                        <div class="mt-2">
                            {% include 'mixins/room_card.html' with room=reservation.room %}
                        </div>
                    </div>
                {% endfor %}
            {% endif %}
        </div>

    </div>

{% endblock %}

templates/reservation/reservation_manage_list.html
{% extends "base.html" %}
{% load i18n manage_reserv %}

{% block page_title %}
    {% trans "Reservation Manage List" %}
{% endblock %}

{% block content %}

        <div class="container mx-auto pb-30">

            <div class="py-12 flex flex-col items-center border-gray-400">
                <div class="flex items-center">
                    <h3 class="text-2xl">{{ user.first_name }}{% trans "'s Reservation Management Room List" %}</h3>
                </div>
            </div>

            <div class="grid md:grid-cols-3 w-full -mx-30 mb-10 items-center">
                {% for room in user.rooms.all %}
                    {% manage_reserv room as manage_reserv %}
                        {% if manage_reserv is not None %}
                            {% for reservation in manage_reserv %}
                                <div class="w-screen px-10">
                                    <a class="ml-6 mb-4 text-base text-xl font-medium text-white bg-green-400 hover:bg-indigo-400 p-1 rounded-md"
                                       href="{% url 'reservations:detail' reservation.pk %}">
                                        {% trans "Manage Reservation" %}
                                    </a>
                                    <div class="mt-2">
                                        {% include 'mixins/room_card.html' with room=room %}
                                    </div>
                                </div>
                            {% endfor %}
                        {% endif %}
                {% endfor %}
            </div>

        </div>

{% endblock %}