config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import os


def trigger_error(request):
    division_by_zero = 1 / 0


urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("reservations/", include("reservations.urls", namespace="reservation")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("lists/", include("lists.urls", namespace="lists")),
    path("conversations/", include("conversations.urls", namespace="conversations")),
    path('sentry-debug/', trigger_error),
    path(os.environ.get("ADMIN_URL", "admin/"), admin.site.urls),
]

if settings.DEBUG:
    # static을 이용해서 settgins.MEDIA_URL과 실제 사진이 저장된 폴더를 연결시켜 주었다
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views
from . import views

app_name = "core"

urlpatterns = [path("", room_views.HomeView.as_view(), name="home"),
               path("copyrights/", views.index, name="copyrights"),
               ]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("login/github/", views.github_login, name="github-login"),
    path("login/github/callback/", views.github_callback, name="github-callback"),
    path("login/kakao/", views.kakao_login, name="kakao-login"),
    path("login/kakao/callback/", views.kakao_callback, name="kakao-callback"),
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("<int:pk>/", views.UserProfileView.as_view(), name="profile"),
    path("verify/<str:key>/", views.complete_verification, name="complete-verification"),
    path("update-profile/", views.UpdateProfileView.as_view(), name="update"),
    path("update-password/", views.UpdatePasswordView.as_view(), name="password"),
    path("switch-hosting/", views.switch_hosting, name="switch-hosting"),
    path("switch-language/", views.switch_language, name="switch-language"),
    path("wish-list/", views.SeeWishList.as_view(), name="see_wish_list"),
]

users/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from django.contrib.auth import password_validation
from django.contrib.auth.forms import UserCreationForm
from . import models


class LoginForm(forms.Form):

    email = forms.EmailField(
        widget=forms.EmailInput(attrs={"placeholder": _("Email")})
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={"placeholder": _("Password")})
    )

    # 변수를 확인하고 싶은 함수를 생성시 clean_변수명()으로 해야한다 - 장고규칙
    # 아니면 명명하지 않고 통합으로 할수도 있다
    # return 값을 주지 않으면 지워버린다
    def clean(self):

        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        try:
            user = models.User.objects.get(email=email)
            if user.check_password(password):
                return self.cleaned_data
            else:
                self.add_error("password", forms.ValidationError(_("Password is wrong")))
        except models.User.DoesNotExist:
            self.add_error("email", forms.ValidationError(_("User does not exist")))


class SignUpForm(forms.ModelForm):

    class Meta:
        model = models.User
        fields = ("first_name", "last_name", "email")
        widgets = {
            "first_name": forms.TextInput(attrs={"placeholder": _("First Name")}),
            "last_name": forms.TextInput(attrs={"placeholder": _("Last Name")}),
            "email": forms.EmailInput(attrs={"placeholder": _("Email")}),
        }

    password = forms.CharField(
        widget=forms.PasswordInput(attrs={"placeholder": _("Password")})
    )
    password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={"placeholder": _("Confirm Password")})
    )

    def clean_email(self):
        email = self.cleaned_data.get("email")
        try:
            models.User.objects.get(email=email)
            raise forms.ValidationError(
                _("That email is already taken"), code="existing_user"
            )
        except models.User.DoesNotExist:
            return email

    def clean_password1(self):
        password1 = self.cleaned_data.get("password")
        password2 = self.cleaned_data.get("password1")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(_("Password confirmation does not match"))
        else:
            return password2

    def save(self, *args, **kwargs):
        user = super().save(commit=False)
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password1")
        birthdate = self.cleaned_data.get("birthdate")

        user.email_verified = True
        user.username = email
        user.birthdate = birthdate
        user.set_password(password)
        user.save()

users/views.py
import os
import requests
from django.http import HttpResponse
from django.utils import translation
from django.utils.translation import gettext_lazy as _
from django.views.generic import FormView, DetailView, UpdateView, TemplateView
from django.shortcuts import redirect, reverse
from django.urls import reverse_lazy
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.views import PasswordChangeView
from django.core.files.base import ContentFile
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.messages.views import SuccessMessageMixin
from . import forms, models, mixins


class LoginView(mixins.LoggedOutOnlyView, FormView):
    template_name = "users/login.html"
    form_class = forms.LoginForm

    def form_valid(self, form):
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password")
        user = authenticate(self.request, username=email, password=password)
        if user is not None:
            is_verified_user = models.User.objects.get(email=email)
            if is_verified_user.email_verified is False:
                # not yet verified
                logout(self.request)
                return redirect(reverse("core:home"))
            else:
                login(self.request, user)
        return super().form_valid(form)

    def get_success_url(self):
        next_arg = self.request.GET.get("next")
        if next_arg is not None:
            return next_arg
        else:
            return reverse("core:home")


def log_out(request):
    messages.info(request, f"See you later {request.user.first_name}")
    logout(request)
    return redirect(reverse("core:home"))


class SignUpView(mixins.LoggedOutOnlyView, FormView):
    template_name = "users/signup.html"
    form_class = forms.SignUpForm
    success_url = reverse_lazy("core:home")

    def form_valid(self, form):
        # forms.py에서 만든 save() 함수
        form.save()
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password1")
        user = authenticate(self.request, username=email, password=password)
        if user is not None:
            login(self.request, user)
        # user.verify_email()
        user.email_verified = True
        return super().form_valid(form)


def complete_verification(request, key):
    try:
        user = models.User.objects.get(email_secret=key)
        user.email_verified = True
        user.email_secret = ""
        user.save()
        # TODO : add success message
    except models.User.DoesNotExist:
        # TODO : add error message
        pass
    return redirect(reverse("core:home"))


def github_login(request):
    if os.environ.get("DEBUG"):
        URL = os.environ.get("LOCAL_URL")
    else:
        URL = os.environ.get("AWS_URL")
    client_id = os.environ.get("GITHUB_ID")
    redirect_uri = f"{URL}/users/login/github/callback"
    # if os.environ.get("DEBUG"):
    return redirect(
        f"https://github.com/login/oauth/authorize?client_id={client_id}&redirect_uri={redirect_uri}&scope=read:user"
    )
    # else:
    #     return redirect(reverse("users:login"))


class GithubException(Exception):
    pass


def github_callback(request):
    try:
        code = request.GET.get("code", None)
        client_id = os.environ.get("GITHUB_ID")
        client_secret = os.environ.get("GITHUB_SECRET")
        if code is not None:
            access_request = requests.post(
                f"https://github.com/login/oauth/access_token?client_id={client_id}&client_secret={client_secret}&code={code}",
                headers={"Accept": "application/json"},
            )
            access_json = access_request.json()
            error = access_json.get("error", None)
            if error is None:
                access_token = access_json.get("access_token", None)
                if access_token is not None:
                    profile_request = requests.get(
                        "https://api.github.com/user",
                        headers={
                            "Authorization": f"token {access_token}",
                            "Accept": "application/json",
                        },
                    )
                    profile_json = profile_request.json()
                    username = profile_json.get("login", None)
                    if username is not None:
                        name = profile_json.get('name')
                        email = profile_json.get('email')
                        bio = profile_json.get('bio')
                        if not name:
                            name = username
                        if not email:
                            email = f"{username}@github.com"
                        if not bio:
                            bio = "None"

                        # login 시 case 별로 분류
                        try:
                            # case1: User is not None (Already Exist)
                            user = models.User.objects.get(email=email)
                            if user.login_method != models.User.LOGIN_GITHUB:
                                # Already signup with Email or Kakao
                                raise GithubException(f"Please login with : {user.login_method}")
                        except models.User.DoesNotExist:
                            # case2: User is None (No that user) -> Create the User
                            user = models.User.objects.create(
                                email=email, first_name=name, username=email, bio=bio,
                                login_method=models.User.LOGIN_GITHUB
                            )
                            # Github 유저이므로 비번은 따로 생성 x (깃헙 계정 유저)
                            user.set_unusable_password()
                            user.save()
                        login(request, user)
                        messages.success(request, f"Welcome back {user.first_name}")
                        return redirect(reverse("core:home"))
                    else:
                        raise GithubException(_("Can't get your profile"))
                else:
                    raise GithubException(_("Can't get Access code"))
            else:
                raise GithubException(_("Error occurred"))
        else:
            raise GithubException(_("Can't get Code"))
    except GithubException as e:
        messages.error(request, e)
        return redirect(reverse("users:login"))


class KakaoException(Exception):
    pass


def kakao_login(request):
    if os.environ.get("DEBUG"):
        URL = os.environ.get("LOCAL_URL")
    else:
        URL = os.environ.get("AWS_URL")
    REST_API_KEY = os.environ.get("KAKAO_KEY")
    REDIRECT_URI = f"{URL}/users/login/kakao/callback"
    return redirect(
        f"https://kauth.kakao.com/oauth/authorize?client_id={REST_API_KEY}&redirect_uri={REDIRECT_URI}&response_type=code"
    )


def kakao_callback(request):
    if os.environ.get("DEBUG"):
        URL = os.environ.get("LOCAL_URL")
    else:
        URL = os.environ.get("AWS_URL")
    KAKAO_ID = os.environ.get("KAKAO_KEY")
    REDIRECT_URI = f"{URL}/users/login/kakao/callback"
    try:
        code = request.GET.get("code", None)
        if code is not None:
            token_request = requests.get(
                f"https://kauth.kakao.com/oauth/token?grant_type=authorization_code&client_id={KAKAO_ID}&redirect_uri={REDIRECT_URI}&code={code}")
            token_json = token_request.json()
            error = token_json.get("error")
            if error is None:
                access_token = token_json.get("access_token")
                profile_request = requests.get(
                    f"https://kapi.kakao.com/v2/user/me",
                    headers={"Authorization": f"Bearer {access_token}"},
                )
                # print(profile_request.json())
                profile_json = profile_request.json()
                kakao_account = profile_json.get("kakao_account")
                email = kakao_account.get("email")

                # 이메일이 없다면 로그인 불가
                if email is None:
                    raise KakaoException(_("Please also give me email"))
                else:
                    profile = kakao_account.get("profile")
                    profile_image = profile.get("profile_image_url")
                    nickname = profile.get("nickname")
                    try:
                        # 이메일이 있다면 로그인
                        user = models.User.objects.get(email=email)
                        if user.login_method != models.User.LOGIN_KAKAO:
                            # 해당 이메일이 이미 카톡이 아닌 다른 걸로 로그인 한 경우
                            raise KakaoException(f"Please log in with :{user.login_method}")
                    except models.User.DoesNotExist:
                        # 이메일이 없다면 해당 이메일로 계정 생성, 저장 후 로그인
                        user = models.User.objects.create(
                            email=email,
                            first_name=nickname,
                            login_method=models.User.LOGIN_KAKAO,
                            email_verified=True,
                            username=nickname,
                        )
                        user.set_unusable_password()
                        user.save()
                        if profile_image is not None:
                            photo_request = requests.get(profile_image)
                            user.avatar.save(
                                f"{nickname}-avatar", ContentFile(photo_request.content)
                            )
                    login(request, user)
                    messages.success(request, f"Welcome back {user.first_name}")
                    return redirect(reverse("core:home"))
            else:
                raise KakaoException(_("Can't get Authorization code"))
        else:
            raise KakaoException(_("something went wrong"))

templates/users/login.html
{%  extends "base.html" %}
{% load i18n %}

{% block page_title %}
    {% trans "Login" %}
{% endblock %}

{% block search-bar %}
{% endblock %}

{% block content %}

    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">

        {% include 'partials/social_login.html' %}

        {% include 'mixins/auth/auth_form.html' with form=form cta="Log in" %}

        <div class="mt-5">
            <span class="mr-2">{% trans "Don't have an account?" %}</span>
            <a href="{% url "users:signup" %}" class="text-green-500 font-medium">{% trans "Sign up" %}</a>
        </div>
    </div>
{% endblock %}

templates/users/signup.html
{%  extends "base.html" %}
{% load i18n %}

{% block page_title %}
    {% trans "Sign Up" %}
{% endblock %}

{% block search-bar %}
{% endblock %}

{% block content %}

    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">

        {% include 'partials/social_login.html' %}

        {% include 'mixins/auth/auth_form.html' with form=form cta="Sign up" %}

        <div class="mt-5">
            <span class="mr-2">{% trans "Have an account?" %}</span>
            <a href="{% url "users:login" %}" class="text-green-500 font-medium">{% trans "Log in" %}</a>
        </div>

    </div>
{% endblock %}

templates/users/update-password.html
{%  extends "base.html" %}
{% load i18n %}

{% block page_title %}
    {% trans "update password" %}
{% endblock %}

{% block search-bar %}
{% endblock %}

{% block content %}

    <div class="min-h-screen">
        <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">

            {% include 'mixins/auth/auth_form.html' with form=form cta="Update password" %}

        </div>
    </div>
{% endblock %}

templates/users/update-profile.html
{%  extends "base.html" %}
{% load i18n %}

{% block page_title %}
    {% trans "update profile" %}
{% endblock %}

{% block search-bar %}
{% endblock %}

{% block content %}

    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">

        {% include 'mixins/auth/auth_form.html' with form=form cta="Update profile" %}

        {% if object.login_method == "email" %}
            <div class="mt-5">
            <a href="{% url "users:password" %}" class="text-green-500 font-medium">{% trans "Change Password" %}</a>
        </div>
        {% endif %}
    </div>
{% endblock %}

templates/users/user_detail.html
{%  extends "base.html" %}
{% load i18n %}

{% block page_title %}
    {{ user_obj.first_name }}{% trans "'s Profile" %}
{% endblock %}

{% block content %}

    <div class="min-h-screen">
        <div class="container  lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">

            {% include "mixins/user_avatar.html" with user=user_obj %}

            <div class="flex items-center">
                <span class="text-3xl mt-3">{{ user_obj.first_name }}</span>
                {% if user_obj.superhost %}
                    <i class="fas fa-check-circle text-green-400 ml-1"></i>
                {% endif %}
            </div>

            <span class="text-lg mt-1 mb-5">{{ user_obj.bio }}</span>

            {% if user == user_obj %}
                <a href="{% url 'users:update' %}" class="btn-link">{% trans "Edit Profile" %}</a>
            {% endif %}
        </div>

        {% if user_obj.rooms.count > 0 %}
            <div class="container flex flex-col items-center mx-auto pb-10">
            <h3 class="mb-12 text-2xl">{{ user_obj.first_name }}{% trans "'s rooms" %}</h3>
            <div class="flex flex-wrap -mx-30 w-full mb-10">
                    {% for room in user_obj.rooms.all %}
                        {% include 'mixins/room_card.html' with room=room %}
                    {% endfor %}
            </div>
        </div>
        {% endif %}
    </div>

{% endblock %}